---
- name: Install Docker Engine and essentials on Ubuntu
  hosts: all
  become: true

  vars:
    docker_user: "{{ ansible_user | default('ubuntu') }}"

  tasks:
    - name: Ensure required base packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: true

    # - name: Remove any existing Docker repository configuration
    #   file:
    #     path: '{{ item }}'
    #     state: absent
    #   loop:
    #     - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
    #     - /etc/apt/sources.list.d/docker.list

    - name: Add Docker's official GPG key to proper location
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Debug architecture and distribution
      debug:
        msg: 'Architecture: {{ ansible_architecture }}, Distribution: {{ ansible_distribution_release }}'

    - name: Set up the Docker repository with correct architecture
      apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true
        mode: '0644'

    # - name: Stop any existing Docker service
    #   systemd:
    #     name: docker
    #     state: stopped
    #   ignore_errors: true

    # - name: Remove any existing Docker packages
    #   apt:
    #     name:
    #       - docker.io
    #       - docker-doc
    #       - docker-compose
    #       - docker-compose-v2
    #       - podman-docker
    #       - containerd
    #       - runc
    #     state: absent
    #     purge: true
    #   ignore_errors: true

    # - name: Clean up any existing Docker directories
    #   file:
    #     path: '{{ item }}'
    #     state: absent
    #   loop:
    #     - /etc/docker
    #     - /var/lib/docker
    #     - /var/lib/containerd
    #   ignore_errors: true

    - name: Install Docker Engine, CLI, and Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure containerd is running before Docker
      systemd:
        name: containerd
        state: started
        enabled: true

    - name: Ensure Docker is running and enabled on boot
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group for rootless usage
      user:
        name: '{{ docker_user }}'
        groups: docker
        append: true

    - name: Verify Docker is installed and running
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Show Docker version
      debug:
        var: docker_version.stdout

    - name: Test Docker with hello-world
      command: docker run --rm hello-world
      register: docker_test
      changed_when: false
      failed_when: "'Hello from Docker!' not in docker_test.stdout"

    - name: Configure Docker daemon for better user experience
      copy:
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "5"
            },
            "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json
        mode: '0644'
        backup: no

    - name: Restart Docker to apply daemon configuration
      systemd:
        name: docker
        state: restarted

    - name: Create Docker config directory for the user
      file:
        path: '/home/{{ docker_user }}/.docker'
        state: directory
        owner: '{{ docker_user }}'
        group: '{{ docker_user }}'
        mode: '0700'

    - name: Add user environment variables for Docker
      blockinfile:
        path: '/home/{{ docker_user }}/.bashrc'
        create: no
        backup: no
        block: |
          # Docker environment variables
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1

    - name: Set correct ownership of .bashrc
      file:
        path: '/home/{{ docker_user }}/.bashrc'
        owner: '{{ docker_user }}'
        group: '{{ docker_user }}'

    - name: Add helpful Docker aliases
      blockinfile:
        path: '/home/{{ docker_user }}/.bashrc'
        create: no
        backup: no
        block: |
          # Docker aliases
          alias dps='docker ps'
          alias dpsa='docker ps -a'
          alias di='docker images'
          alias drm='docker rm'
          alias drmi='docker rmi'
          alias dstop='docker stop'
          alias dstart='docker start'
          alias dc='docker compose'
          alias dcup='docker compose up -d'
          alias dcdown='docker compose down'
          alias dlogs='docker logs'
          alias dexec='docker exec -it'

    - name: Set correct ownership of .bashrc after aliases
      file:
        path: '/home/{{ docker_user }}/.bashrc'
        owner: '{{ docker_user }}'
        group: '{{ docker_user }}'
